mt4-mobile-project/nunu-mobile-app

- mobile/.eslintrc.js
- mobile/components/HelloWave.tsx
- mobile/package.json
- mobile/pnpm-lock.yaml
> feat : add eslint

- mobile/app/(tabs)/_layout.tsx
- mobile/components/ExternalLink.tsx
- mobile/components/HapticTab.tsx
- mobile/components/ui/IconSymbol.tsx
- mobile/pnpm-lock.yaml
- mobile/tsconfig.json
> fix : fix tsconfig & some fils errors

- .github/workflows/ci.yml
- mobile/components/HapticTab.tsx
- mobile/components/ui/TabBarBackground.ios.tsx
- mobile/pnpm-lock.yaml
> ci : add typecheck

- backend/src/main/java/com/example/api/controllers/ProfileController.java
- backend/src/main/java/com/example/api/dtos/ProfileRequestDto.java
- backend/src/main/java/com/example/api/dtos/ProfileResponseDto.java
- backend/src/main/java/com/example/api/entities/Profile.java
- backend/src/main/java/com/example/api/mappers/ProfileMapper.java
- backend/src/main/java/com/example/api/repositories/ProfileRepository.java
- backend/src/main/java/com/example/api/services/ProfileService.java
> feat : add user profile functionality

- backend/dump/init.sql
- backend/pom.xml
- backend/src/main/java/com/example/api/controllers/EventController.java
- backend/src/main/java/com/example/api/dtos/AddressRequestDto.java
- backend/src/main/java/com/example/api/dtos/AddressResponseDto.java
- backend/src/main/java/com/example/api/dtos/EventRequestDto.java
- backend/src/main/java/com/example/api/dtos/EventResponseDto.java
- backend/src/main/java/com/example/api/dtos/EventUpdateDto.java
- backend/src/main/java/com/example/api/dtos/UserResponseDto.java
- backend/src/main/java/com/example/api/entities/Address.java
- backend/src/main/java/com/example/api/entities/Event.java
- backend/src/main/java/com/example/api/entities/EventParticipant.java
- backend/src/main/java/com/example/api/exceptions/GlobalExceptionHandler.java
- backend/src/main/java/com/example/api/mappers/AddressMapper.java
- backend/src/main/java/com/example/api/mappers/EventMapper.java
- backend/src/main/java/com/example/api/mappers/UserMapper.java
- backend/src/main/java/com/example/api/repositories/EventParticipantRepository.java
- backend/src/main/java/com/example/api/repositories/EventRepository.java
- backend/src/main/java/com/example/api/services/AddressService.java
- backend/src/main/java/com/example/api/services/EventService.java
> feat : add event management features with address

- mobile/src/app/(tabs)/index.tsx
- mobile/src/components/atoms/inputs/input.tsx
> Style: create component (atomes) and variants for input

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/index.tsx
- mobile/src/components/atoms/buttons/label-button.tsx
> feat label button

- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/_layout.tsx
- mobile/src/app/(tabs)/events.tsx
- mobile/src/app/(tabs)/profil.tsx
- mobile/src/app/event/[id].tsx
- mobile/src/app/vitoexample.tsx
> feat : add example router

- mobile/src/components/atoms/buttons/icon-button.tsx
> feat : add icon button

- mobile/src/app/(tabs)/events.tsx
- mobile/src/app/(tabs)/profil.tsx
- mobile/src/app/event/[id].tsx
- mobile/src/app/vitoexample.tsx
> fix : fix pages name

- mobile/src/app/(tabs)/index.tsx
- mobile/src/components/atoms/inputs/input.tsx
> 113 feat icone to input composant

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/profil.tsx
- mobile/src/components/atoms/profile-cards/profil-image.tsx
- mobile/src/components/atoms/profile-cards/profil-name.tsx
- mobile/src/components/molecules/profile-card/profil-card.tsx
> style: add atomes and molecules for profile-card

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/index.tsx
- mobile/src/services/auth.ts
- mobile/src/services/user.ts
- mobile/src/types/user.ts
- mobile/src/utils/api.ts
- mobile/src/utils/asyncStorageToken.ts
> feat : api fetching util with asyncstorage and authorization

- backend/src/main/java/com/example/api/controllers/UserController.java
- backend/src/main/java/com/example/api/services/UserService.java
> feat: add endpoint to retrieve user by username

- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/index.tsx
- mobile/src/components/atoms/inputs/input.tsx
- mobile/src/components/molecules/users-card/users-card.tsx
- mobile/src/hooks/useUsers.ts
- mobile/src/services/user.ts
> 39 feat lister toutes les utilisateurs qui sont inscrits

- .gitignore
- backend/src/main/java/com/example/api/config/SecurityConfig.java
- backend/src/main/java/com/example/api/controllers/FileController.java
- backend/src/main/resources/application.properties
> feat : add functionality to serve uploaded images and configure static path

- .gitignore
- backend/src/main/java/com/example/api/controllers/FileController.java
- backend/src/main/resources/application.properties
> 94 feat serve uploaded images and static images

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/_layout.tsx
- mobile/src/app/(tabs)/index.tsx
- mobile/src/app/(tabs)/temporary.tsx
- mobile/src/app/temporary/form.tsx
- mobile/src/components/atoms/inputs/input.tsx
- mobile/src/components/molecules/form/form.tsx
- mobile/src/components/molecules/users-card/users-card.tsx
- mobile/src/services/user.ts
- mobile/src/utils/form.ts
> 126 feat create form component

- mobile/src/app/(tabs)/index.tsx
- mobile/src/hooks/useUsers.ts
- mobile/src/services/user.ts
> feat filter users by username

- mobile/src/app/(tabs)/events.tsx
- mobile/src/app/(tabs)/profil.tsx
- mobile/src/components/atoms/inputs/input.tsx
- mobile/src/components/molecules/confirmation-buttons/confirmation-button.tsx
- mobile/src/components/molecules/profile-card/profil-card.tsx
- mobile/src/configs/inputs/profile-input.config.ts
- mobile/src/configs/inputs/register-input.config.ts
- mobile/src/utils/generator/input-generator.tsx
> style and feat: styling profil page and adding an input generator

- mobile/src/hooks/useAuth.ts
- mobile/src/services/auth.ts
> 26 feat login

- mobile/src/app/(tabs)/events.tsx
- mobile/src/components/molecules/event-card/event-card.tsx
- mobile/src/hooks/useEvent.ts
- mobile/src/hooks/users/useUsers.ts
- mobile/src/services/event.ts
- mobile/src/types/event.ts
- mobile/src/utils/api.ts
> 127 feat créer un composant event card et filtre events

- mobile/src/app/(tabs)/events.tsx
- mobile/src/components/molecules/event-card/event-card.tsx
- mobile/src/hooks/events/useEvents.ts
- mobile/src/services/event.ts
- mobile/src/services/events.ts
- mobile/src/services/files.ts
- mobile/src/types/event.ts
- mobile/src/types/files.ts
> 148 refacto handle other type for get file

- mobile/src/app/(tabs)/events.tsx
- mobile/src/app/(tabs)/map.tsx
- mobile/src/components/molecules/cards/event-details.tsx
- mobile/src/components/molecules/forms/event-creation-form.tsx
- mobile/src/components/organisms/lists/event-list-content.tsx
- mobile/src/hooks/auth/useAuth.ts
- mobile/src/hooks/events/useEventForm.ts
- mobile/src/hooks/events/useEvents.ts
- mobile/src/hooks/events/useJoinEvent.ts
- mobile/src/hooks/events/useJoinedEvents.ts
- mobile/src/hooks/events/useMyEvents.ts
- mobile/src/services/events.ts
- mobile/src/types/events.ts
> 160 feat join event

- mobile/package.json
- mobile/pnpm-lock.yaml
- mobile/src/app/(tabs)/events.tsx
- mobile/src/components/molecules/cards/event-details.tsx
- mobile/src/components/organisms/lists/event-list-content.tsx
- mobile/src/hooks/events/__tests__/useEventFilters.test.ts
- mobile/src/hooks/events/useEventForm.ts
> 164 fix routes order

- mobile/src/app/_layout.tsx
- mobile/src/app/room/[id].tsx
- mobile/src/hooks/messages/useMessages.ts
- mobile/src/services/message.ts
- mobile/src/types/message.ts
> feat : display messages from db

- backend/src/main/java/com/example/api/controllers/RoomController.java
- backend/src/main/java/com/example/api/repositories/RoomRepository.java
- backend/src/main/java/com/example/api/services/RoomService.java
- mobile/src/app/(tabs)/index.tsx
- mobile/src/hooks/rooms/useCreateRoom.ts
- mobile/src/hooks/rooms/useRoom.ts
- mobile/src/hooks/rooms/useRoomBetweenByUser1IdUser2Id.ts
- mobile/src/services/rooms.ts
> 166 refacto room
